### ISSUE TITLE
Crash when pressing Ctrl + Menu Key

### ISSUE THREAD

**Issue by lordmauve** [lordmauve/pgzero#18]
Originally reported by: **Daniel Pope (Bitbucket: [lordmauve](https://bitbucket.org/lordmauve), GitHub: [lordmauve](https://github.com/lordmauve))**

----------------------------------------

When I press Ctrl + Menu Key, Pygame Zero crashes with the traceback:

    Traceback (most recent call last):                                          
      File "/home/mauve/.virtualenvs/pgzero/bin/pgzrun", line 9, in <module>       
        load_entry_point('pgzero==1.0.2', 'console_scripts', 'pgzrun')()           
      File "/home/mauve/.virtualenvs/pgzero/lib/python3.4/site-packages/pgzero/runner.py", line 38, in main
        PGZeroGame(mod).run()                                                      
      File "/home/mauve/.virtualenvs/pgzero/lib/python3.4/site-packages/pgzero/game.py", line 173, in run 
        self.dispatch_event(event)                                                 
      File "/home/mauve/.virtualenvs/pgzero/lib/python3.4/site-packages/pgzero/game.py", line 109, in dispatch_event
        handler(event)                                                             
      File "/home/mauve/.virtualenvs/pgzero/lib/python3.4/site-packages/pgzero/game.py", line 103, in <lambda>
        return lambda event: handler(**prep_args(event))                           
      File "/home/mauve/.virtualenvs/pgzero/lib/python3.4/site-packages/pgzero/game.py", line 102, in prep_args
        return {name: get(event) for name, get in param_handlers}                  
      File "/home/mauve/.virtualenvs/pgzero/lib/python3.4/site-packages/pgzero/game.py", line 102, in <dictcomp>
        return {name: get(event) for name, get in param_handlers}                  
      File "/home/mauve/.virtualenvs/pgzero/lib/python3.4/site-packages/pgzero/game.py", line 92, in <lambda>
        return lambda event: mapper(getter(event))                                 
      File "/usr/lib/python3.4/enum.py", line 222, in __call__                     
        return cls.__new__(cls, value)                                             
      File "/usr/lib/python3.4/enum.py", line 457, in __new__                      
        raise ValueError("%r is not a valid %s" % (value, cls.__name__))           
    ValueError: 314 is not a valid keys  

----------------------------------------
- Bitbucket: https://bitbucket.org/lordmauve/pgzero/issue/18

**Comment by lordmauve** [comment]
*Original comment by* **Daniel Pope (Bitbucket: [lordmauve](https://bitbucket.org/lordmauve), GitHub: [lordmauve](https://github.com/lordmauve))**:

----------------------------------------

Fix crash with unusual mouse buttons or key combinations (closes issue #18)
