### ISSUE TITLE
install fails on ubuntu

### ISSUE THREAD

**Issue by tartley** [lordmauve/pgzero#209]
**Update**: I just realized this works fine using my system Python3.7, and only fails using my personally compiled Python3.8, so you can probably close this.

Shown here with `--no-cache-dir` to make sure my cache isn't somehow messing things up. The same happens without it.

```
$ pip install --no-cache-dir pgzero
Collecting pgzero
  Downloading https://files.pythonhosted.org/packages/48/e5/e5f14292373cb5fc7539aa01307b184c1e3c954d68945d8c44778669dd82/pgzero-1.2-py3-none-any.whl (69kB)
     |████████████████████████████████| 71kB 1.7MB/s 
Collecting pygame<2.0,>=1.9.2
  Downloading https://files.pythonhosted.org/packages/0f/9c/78626be04e193c0624842090fe5555b3805c050dfaa81c8094d6441db2be/pygame-1.9.6.tar.gz (3.2MB)
     |████████████████████████████████| 3.2MB 4.6MB/s 
    ERROR: Command errored out with exit status 1:
     command: /home/jhartley/.virtualenvs/zgame/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fyoihzi1/pygame/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fyoihzi1/pygame/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-fyoihzi1/pygame/pip-egg-info
         cwd: /tmp/pip-install-fyoihzi1/pygame/
    Complete output (18 lines):
    
    
    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using UNIX configuration...
    
    
    Hunting dependencies...
    SDL     : found 1.2.15
    FONT    : not found
    IMAGE   : not found
    MIXER   : not found
    PNG     : found
    JPEG    : not found
    SCRAP   : found
    PORTMIDI: not found
    PORTTIME: not found
    FREETYPE: found 22.1.16
    Missing dependencies
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Logs produced using `--log log` are lengthy, the relevant bit is:
```
2019-11-26T11:12:04,957 Collecting pygame<2.0,>=1.9.2
2019-11-26T11:12:04,957   Created temporary directory: /tmp/pip-unpack-1sknpp7i
2019-11-26T11:12:04,969   Using cached https://files.pythonhosted.org/packages/0f/9c/78626be04e193c0624842090fe5555b3805c050dfaa81c8094d6441db2be/pygame-1.9.6.tar.gz
2019-11-26T11:12:05,202   Added pygame<2.0,>=1.9.2 from https://files.pythonhosted.org/packages/0f/9c/78626be04e193c0624842090fe5555b3805c050dfaa81c8094d6441db2be/pygame-1.9.6.tar.gz#sha256=301c6428c0880ecd4a9e3951b80e539c33863b6ff356a443db1758de4f297957 (from pgzero) to build tracker '/tmp/pip-req-tracker-pdrdt5_p'
2019-11-26T11:12:05,202     Running setup.py (path:/tmp/pip-install-5r44blqb/pygame/setup.py) egg_info for package pygame
2019-11-26T11:12:05,202     Running command python setup.py egg_info


2019-11-26T11:12:05,346     WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
2019-11-26T11:12:05,346     Using UNIX configuration...


2019-11-26T11:12:05,423     Hunting dependencies...
2019-11-26T11:12:05,423     SDL     : found 1.2.15
2019-11-26T11:12:05,423     FONT    : not found
2019-11-26T11:12:05,423     IMAGE   : not found
2019-11-26T11:12:05,423     MIXER   : not found
2019-11-26T11:12:05,423     PNG     : found
2019-11-26T11:12:05,423     JPEG    : not found
2019-11-26T11:12:05,423     SCRAP   : found
2019-11-26T11:12:05,423     PORTMIDI: not found
2019-11-26T11:12:05,423     PORTTIME: not found
2019-11-26T11:12:05,423     FREETYPE: found 22.1.16
2019-11-26T11:12:05,423     Missing dependencies
2019-11-26T11:12:05,443 Cleaning up...
2019-11-26T11:12:05,443   Removing source in /tmp/pip-install-5r44blqb/pygame
2019-11-26T11:12:05,476 Removed pygame<2.0,>=1.9.2 from https://files.pythonhosted.org/packages/0f/9c/78626be04e193c0624842090fe5555b3805c050dfaa81c8094d6441db2be/pygame-1.9.6.tar.gz#sha256=301c6428c0880ecd4a9e3951b80e539c33863b6ff356a443db1758de4f297957 (from pgzero) from build tracker '/tmp/pip-req-tracker-pdrdt5_p'
2019-11-26T11:12:05,477 Removed build tracker '/tmp/pip-req-tracker-pdrdt5_p'
2019-11-26T11:12:05,477 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
2019-11-26T11:12:05,477 Exception information:
2019-11-26T11:12:05,477 Traceback (most recent call last):
2019-11-26T11:12:05,477   File "/home/jhartley/.virtualenvs/zgame/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
2019-11-26T11:12:05,477     status = self.run(options, args)
2019-11-26T11:12:05,477   File "/home/jhartley/.virtualenvs/zgame/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 382, in run
2019-11-26T11:12:05,477     resolver.resolve(requirement_set)
2019-11-26T11:12:05,477   File "/home/jhartley/.virtualenvs/zgame/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
2019-11-26T11:12:05,477     self._resolve_one(requirement_set, req)
2019-11-26T11:12:05,477   File "/home/jhartley/.virtualenvs/zgame/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
2019-11-26T11:12:05,477     abstract_dist = self._get_abstract_dist_for(req_to_install)
2019-11-26T11:12:05,477   File "/home/jhartley/.virtualenvs/zgame/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 312, in _get_abstract_dist_for
2019-11-26T11:12:05,477     abstract_dist = self.preparer.prepare_linked_requirement(
2019-11-26T11:12:05,477   File "/home/jhartley/.virtualenvs/zgame/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 223, in prepare_linked_requirement
2019-11-26T11:12:05,477     abstract_dist = _get_prepared_distribution(
2019-11-26T11:12:05,477   File "/home/jhartley/.virtualenvs/zgame/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 49, in _get_prepared_distribution
2019-11-26T11:12:05,477     abstract_dist.prepare_distribution_metadata(finder, build_isolation)
2019-11-26T11:12:05,477   File "/home/jhartley/.virtualenvs/zgame/lib/python3.8/site-packages/pip/_internal/distributions/source/legacy.py", line 39, in prepare_distribution_metadata
2019-11-26T11:12:05,477     self.req.prepare_metadata()
2019-11-26T11:12:05,477   File "/home/jhartley/.virtualenvs/zgame/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 563, in prepare_metadata
2019-11-26T11:12:05,477     self.metadata_directory = metadata_generator(self)
2019-11-26T11:12:05,477   File "/home/jhartley/.virtualenvs/zgame/lib/python3.8/site-packages/pip/_internal/operations/generate_metadata.py", line 121, in _generate_metadata_legacy
2019-11-26T11:12:05,477     call_subprocess(
2019-11-26T11:12:05,477   File "/home/jhartley/.virtualenvs/zgame/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
2019-11-26T11:12:05,477     raise InstallationError(exc_msg)
2019-11-26T11:12:05,477 pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

So, I can infer that pgzero is installing pygame, which requires me to install all the correct bits of SDL beforehand. But pgzero's intended audience will not be able to debug that, so I think that solution needs inserting into pgzero's installation documentation.

This is all using:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan
$ pip --version
pip 19.3.1 from /home/jhartley/.virtualenvs/zgame/lib/python3.8/site-packages/pip (python 3.8)
```

Best!

**Comment by tartley** [comment]
Ah, it works using my Python3.7, but does not using my Python3.8 (compiled by me.) So probably all my fault, not a concern for you.

**Comment by lordmauve** [comment]
This is due to Pygame not providing Python 3.8 wheels. They'll probably get around to fixing that soon, but we can nag.

**Comment by lordmauve** [comment]
Ah, they have released wheels, but only for Windows so far.
