### ISSUE TITLE
music object

### ISSUE THREAD

**Issue by lordmauve** [lordmauve/pgzero#31]
Originally reported by: **David Bern (Bitbucket: [drobban](https://bitbucket.org/drobban), GitHub: [drobban](https://github.com/drobban))**

----------------------------------------

Trying to use music object to play music.
This is the Traceback I get when trying to pgzrun the examples/basic/music.py, identical traceback when trying to use music in other projects.

Traceback (most recent call last):
  File "/usr/local/bin/pgzrun", line 9, in <module>
    load_entry_point('pgzero==1.1rc1', 'console_scripts', 'pgzrun')()
  File "/usr/local/lib/python3.4/site-packages/pgzero/runner.py", line 42, in main
    PGZeroGame(mod).run()
  File "/usr/local/lib/python3.4/site-packages/pgzero/game.py", line 195, in run
    self.dispatch_event(event)
  File "/usr/local/lib/python3.4/site-packages/pgzero/game.py", line 131, in dispatch_event
    handler(event)
  File "/usr/local/lib/python3.4/site-packages/pgzero/game.py", line 125, in <lambda>
    return lambda event: handler(**prep_args(event))
  File "music.py", line 28, in on_mouse_down
    music.play(t)
  File "/usr/local/lib/python3.4/site-packages/pgzero/music.py", line 51, in play
    _play(name, -1)
  File "/usr/local/lib/python3.4/site-packages/pgzero/music.py", line 40, in _play
    _music.load(path)
pygame.error

----------------------------------------
- Bitbucket: https://bitbucket.org/lordmauve/pgzero/issue/31

**Comment by lordmauve** [comment]
*Original comment by* **David Bern (Bitbucket: [drobban](https://bitbucket.org/drobban), GitHub: [drobban](https://github.com/drobban))**:

----------------------------------------

libsdl related error.
Caused by a bad install.

Perhaps it could be a good idea to warn OS X users about conflicting installs of sdl if they use both brew and mac ports.
