### ISSUE TITLE
No support for framebuffer rendering in pygamezero ?

### ISSUE THREAD

**Issue by lordmauve** [lordmauve/pgzero#49]
Originally reported by: **brice.copy@cern.ch (Bitbucket: [bcopy](https://bitbucket.org/bcopy), GitHub: [bcopy](https://github.com/bcopy))**

----------------------------------------

On touchscreens, Pygame can render directly to framebuffer.
However, the Pygamezero runner seems to have a problem with screen setup :

  File "/usr/local/lib/python3.4/dist-packages/pgzero/runner.py", line 81, in main
    pygame.display.set_mode((100, 100), DISPLAY_FLAGS)
pygame.error: Couldn't set console screen info

Setting the usual SDL enviroment variables to point Pygame to the framebuffer in the usual way does not work for Pygamezero :
----
pgtest.py
```
#!python
WIDTH = 300
HEIGHT = 300
def draw():
    screen.fill((128, 0, 0))
```

----

Running the above script  (even as sudo) with :

```
#!shell
SDL_VIDEODRIVER=fbcon SDL_FBDEV=/dev/fb0 pgzrun pgztest.py 
```

Gives the following :

```
#!shell
Traceback (most recent call last):
  File "/usr/local/bin/pgzrun", line 9, in <module>
    load_entry_point('pgzero==1.1', 'console_scripts', 'pgzrun')()
  File "/usr/local/lib/python3.4/dist-packages/pgzero/runner.py", line 81, in main
    pygame.display.set_mode((100, 100), DISPLAY_FLAGS)
pygame.error: Couldn't set console screen info

```

----
I was wondering whether one could use pygamezero without the pgzrun runner utility  (and perhaps bypass this forceful mode setting ?).

----------------------------------------
- Bitbucket: https://bitbucket.org/lordmauve/pgzero/issue/49

**Comment by lordmauve** [comment]
*Original comment by* **brice.copy@cern.ch (Bitbucket: [bcopy](https://bitbucket.org/bcopy), GitHub: [bcopy](https://github.com/bcopy))**:

----------------------------------------

Note that commenting out the offending line in runner.py, and calling 


```
#!python
import pygame, sys, os
os.environ["SDL_FBDEV"] = "/dev/fb0"
pygame.init()

pygame.display.set_mode((720,480),pygame.FULLSCREEN)
pygame.display.init()

```
at the beginning of the script fixes the issue.
Without X available, the graphical mode cannot be set to an arbitrary value.
Replacing

```
#!python
pygame.display.set_mode((100,100),DISPLAY_FLAGS)
```

by 
```
#!python
pygame.display.set_mode((720,480),pygame.FULLSCREEN)

```
in runner.py also solves the problem for me.

So could pygamezero not make any assumption on the display mode, and possibly provide input parameters to set those before invoking any pygame calls ?

**Comment by lordmauve** [comment]
*Original comment by* **Steve Clement (Bitbucket: [SteveClement](https://bitbucket.org/SteveClement), GitHub: [SteveClement](https://github.com/SteveClement))**:

----------------------------------------

Dear

I suggest implementing this somewhere near the PGZeroGame Class in game.py (where also DISPLAY_FLAGS = 0 is set)

The function reinit_screen "getattrs" the WIDTH and HEIGHT and could check for a bool à la FULLSCREEN or perhaps if more concise/compatible/working an FB bool.

Last time I tried to run some pygame code FULLSCREEN it was a rather buggy affair.
But the bugginess was mostly due to toggling in and out of fullscreen.

Cheers,

Steve

**Comment by lordmauve** [comment]
*Original comment by* **brice.copy@cern.ch (Bitbucket: [bcopy](https://bitbucket.org/bcopy), GitHub: [bcopy](https://github.com/bcopy))**:

----------------------------------------

Hi, any update on this ?
