### ISSUE TITLE
NameError: name 'DEFAULT_FONT_NAME' is not defined

### ISSUE THREAD

**Issue by lordmauve** [lordmauve/pgzero#52]
Originally reported by: **Steve Clement (Bitbucket: [SteveClement](https://bitbucket.org/SteveClement), GitHub: [SteveClement](https://github.com/SteveClement))**

----------------------------------------

Running the example ptext.py yields an error… Perhaps I missed an installation step?

Is a font name mandatory? Surely not.

I saw some sysfont code, I will double check to see if I missed something.

Testing on OSX Sierra.

```
#!bash

$ pgzrun ptext.py
Traceback (most recent call last):
  File "/usr/local/bin/pgzrun", line 11, in <module>
    load_entry_point('pgzero==1.1', 'console_scripts', 'pgzrun')()
  File "/usr/local/lib/python3.6/site-packages/pgzero/runner.py", line 89, in main
    PGZeroGame(mod).run()
  File "/usr/local/lib/python3.6/site-packages/pgzero/game.py", line 223, in run
    draw()
  File "ptext.py", line 128, in draw
    shadow=(1, 1)
  File "/usr/local/lib/python3.6/site-packages/pgzero/screen.py", line 61, in text
    ptext.draw(*args, surf=self._surf, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pgzero/ptext.py", line 441, in draw
    lineheight, angle, cache)
  File "/usr/local/lib/python3.6/site-packages/pgzero/ptext.py", line 269, in getsurf
    width=width, widthem=widthem, strip=strip)
  File "/usr/local/lib/python3.6/site-packages/pgzero/ptext.py", line 84, in wrap
    bold, italic, underline)
  File "/usr/local/lib/python3.6/site-packages/pgzero/loaders.py", line 222, in getfont
    fontname = DEFAULT_FONT_NAME
NameError: name 'DEFAULT_FONT_NAME' is not defined
```

----------------------------------------
- Bitbucket: https://bitbucket.org/lordmauve/pgzero/issue/52

**Comment by lordmauve** [comment]
*Original comment by* **Daniel Pope (Bitbucket: [lordmauve](https://bitbucket.org/lordmauve), GitHub: [lordmauve](https://github.com/lordmauve))**:

----------------------------------------

Fix: NameError: name 'DEFAULT_FONT_NAME' is not defined (closes #52)
