### ISSUE TITLE
Test suite crash on Linux

### ISSUE THREAD

**Issue by lordmauve** [lordmauve/pgzero#55]
Originally reported by: **encukou (Bitbucket: [encukou](https://bitbucket.org/encukou), GitHub: [encukou](https://github.com/encukou))**

----------------------------------------

The test suite crashes with a freshly cloned copy of Pygame Zero.
I'm on Fedora 26 with X11. I've installed using `pip install -e.`, which pulled in `pygame-1.9.3-cp36-cp36m-manylinux1_x86_64.whl`.

----------------------------------------
- Bitbucket: https://bitbucket.org/lordmauve/pgzero/issue/55

**Comment by lordmauve** [comment]
*Original comment by* **encukou (Bitbucket: [encukou](https://bitbucket.org/encukou), GitHub: [encukou](https://github.com/encukou))**:

----------------------------------------

Also happens if I compile pygame (`pip install --no-binary :all: -e .`), with `SDL*-devel` installed from system repos.

No longer happens when I disable these tests from `test_sound_formats`:

* `test_load_11kgsm`
* `test_load_11kulaw`
* `test_load_8kmp316`
* `test_load_8kmp38`.

**Comment by tonysimpson** [comment]
Related https://github.com/pygame/pygame/issues/406

**Comment by tonysimpson** [comment]
I don't get this issue when building pygame from source, I suspect the manylinux build might be the cause.
Tested building Pygame 1.9.4 from source on Arch with (from pacman) sdl 1.2.15-7 and sdl_mixer 1.2.12-5.
output:
```
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    sounds.load('wav22kgsm')
  File "/home/tsimpson/work/pgzero/pgzero/loaders.py", line 138, in load
    res = self.cache[key] = self._load(p, *args, **kwargs)
  File "/home/tsimpson/work/pgzero/pgzero/loaders.py", line 192, in _load
    """.format(path, fmt).strip()) from None
pgzero.loaders.UnsupportedFormat: '/home/tsimpson/work/pgzero/test/sounds/wav22kgsm.wav' is not in a supported audio format.

It appears to be:

    WAV audio encoded as GSM 6.10, mono, 22050 Hz

Pygame supports only uncompressed WAV files (PCM or ADPCM) and compressed
Ogg Vorbis files. Try re-encoding the sound file, for example using Audacity:

    http://audacityteam.org/
```

**Comment by tonysimpson** [comment]
Issue identified as a known issue in sdl mixer - updated here https://github.com/pygame/pygame/issues/406
