### ISSUE TITLE
Unsupported sound files format in tests

### ISSUE THREAD

**Issue by lordmauve** [lordmauve/pgzero#58]
Originally reported by: **Lumír Balhar (Bitbucket: [frenzymadness](https://bitbucket.org/frenzymadness), GitHub: [frenzymadness](https://github.com/frenzymadness))**

----------------------------------------

Hello.

When I try to run tests it fails because files in test/sounds seems to be in unsupported format.

```
======================================================================
ERROR: test_load_22k16bitpcm (test.test_sound_formats.SoundFormatsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/lordmauve-pgzero-de127c76f809/test/test_sound_formats.py", line 26, in test_load_22k16bitpcm
    self.assert_loadable('wav22k16bitpcm')
  File "/builddir/build/BUILD/lordmauve-pgzero-de127c76f809/test/test_sound_formats.py", line 15, in assert_loadable
    s = sounds.load(name)
  File "/builddir/build/BUILD/lordmauve-pgzero-de127c76f809/pgzero/loaders.py", line 135, in load
    res = self.cache[key] = self._load(p, *args, **kwargs)
  File "/builddir/build/BUILD/lordmauve-pgzero-de127c76f809/pgzero/loaders.py", line 189, in _load
    """.format(path, fmt).strip()) from None
pgzero.loaders.UnsupportedFormat: '/builddir/build/BUILD/lordmauve-pgzero-de127c76f809/test/sounds/wav22k16bitpcm.wav' is not in a supported audio format.

It appears to be:

    WAV audio encoded as Microsoft PCM, 16 bit, mono, 22050 Hz

Pygame supports only uncompressed WAV files (PCM or ADPCM) and compressed
Ogg Vorbis files. Try re-encoding the sound file, for example using Audacity:

    http://audacityteam.org/

======================================================================
ERROR: test_load_22k8bitpcm (test.test_sound_formats.SoundFormatsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/lordmauve-pgzero-de127c76f809/test/test_sound_formats.py", line 29, in test_load_22k8bitpcm
    self.assert_loadable('wav22k8bitpcm')
  File "/builddir/build/BUILD/lordmauve-pgzero-de127c76f809/test/test_sound_formats.py", line 15, in assert_loadable
    s = sounds.load(name)
  File "/builddir/build/BUILD/lordmauve-pgzero-de127c76f809/pgzero/loaders.py", line 135, in load
    res = self.cache[key] = self._load(p, *args, **kwargs)
  File "/builddir/build/BUILD/lordmauve-pgzero-de127c76f809/pgzero/loaders.py", line 189, in _load
    """.format(path, fmt).strip()) from None
pgzero.loaders.UnsupportedFormat: '/builddir/build/BUILD/lordmauve-pgzero-de127c76f809/test/sounds/wav22k8bitpcm.wav' is not in a supported audio format.

It appears to be:

    WAV audio encoded as Microsoft PCM, 8 bit, mono, 22050 Hz

Pygame supports only uncompressed WAV files (PCM or ADPCM) and compressed
Ogg Vorbis files. Try re-encoding the sound file, for example using Audacity:

    http://audacityteam.org/

======================================================================
ERROR: test_load_22kadpcm (test.test_sound_formats.SoundFormatsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/lordmauve-pgzero-de127c76f809/test/test_sound_formats.py", line 32, in test_load_22kadpcm
    self.assert_loadable('wav22kadpcm')
  File "/builddir/build/BUILD/lordmauve-pgzero-de127c76f809/test/test_sound_formats.py", line 15, in assert_loadable
    s = sounds.load(name)
  File "/builddir/build/BUILD/lordmauve-pgzero-de127c76f809/pgzero/loaders.py", line 135, in load
    res = self.cache[key] = self._load(p, *args, **kwargs)
  File "/builddir/build/BUILD/lordmauve-pgzero-de127c76f809/pgzero/loaders.py", line 189, in _load
    """.format(path, fmt).strip()) from None
pgzero.loaders.UnsupportedFormat: '/builddir/build/BUILD/lordmauve-pgzero-de127c76f809/test/sounds/wav22kadpcm.wav' is not in a supported audio format.

It appears to be:

    WAV audio encoded as Microsoft ADPCM, mono, 22050 Hz

Pygame supports only uncompressed WAV files (PCM or ADPCM) and compressed
Ogg Vorbis files. Try re-encoding the sound file, for example using Audacity:

    http://audacityteam.org/

======================================================================
ERROR: test_load_vorbis1 (test.test_sound_formats.SoundFormatsTest)
Load OGG Vorbis with .ogg extension.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/lordmauve-pgzero-de127c76f809/test/test_sound_formats.py", line 60, in test_load_vorbis1
    self.assert_loadable('vorbis1')
  File "/builddir/build/BUILD/lordmauve-pgzero-de127c76f809/test/test_sound_formats.py", line 15, in assert_loadable
    s = sounds.load(name)
  File "/builddir/build/BUILD/lordmauve-pgzero-de127c76f809/pgzero/loaders.py", line 135, in load
    res = self.cache[key] = self._load(p, *args, **kwargs)
  File "/builddir/build/BUILD/lordmauve-pgzero-de127c76f809/pgzero/loaders.py", line 189, in _load
    """.format(path, fmt).strip()) from None
pgzero.loaders.UnsupportedFormat: '/builddir/build/BUILD/lordmauve-pgzero-de127c76f809/test/sounds/vorbis1.ogg' is not in a supported audio format.

It appears to be:

    Unknown format (not RIFF WAVE)

Pygame supports only uncompressed WAV files (PCM or ADPCM) and compressed
Ogg Vorbis files. Try re-encoding the sound file, for example using Audacity:

    http://audacityteam.org/

======================================================================
ERROR: test_load_vorbis2 (test.test_sound_formats.SoundFormatsTest)
Load OGG Vorbis with .oga extension.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/lordmauve-pgzero-de127c76f809/test/test_sound_formats.py", line 64, in test_load_vorbis2
    self.assert_loadable('vorbis2')
  File "/builddir/build/BUILD/lordmauve-pgzero-de127c76f809/test/test_sound_formats.py", line 15, in assert_loadable
    s = sounds.load(name)
  File "/builddir/build/BUILD/lordmauve-pgzero-de127c76f809/pgzero/loaders.py", line 135, in load
    res = self.cache[key] = self._load(p, *args, **kwargs)
  File "/builddir/build/BUILD/lordmauve-pgzero-de127c76f809/pgzero/loaders.py", line 189, in _load
    """.format(path, fmt).strip()) from None
pgzero.loaders.UnsupportedFormat: '/builddir/build/BUILD/lordmauve-pgzero-de127c76f809/test/sounds/vorbis2.oga' is not in a supported audio format.

It appears to be:

    Unknown format (not RIFF WAVE)

Pygame supports only uncompressed WAV files (PCM or ADPCM) and compressed
Ogg Vorbis files. Try re-encoding the sound file, for example using Audacity:

    http://audacityteam.org/

----------------------------------------------------------------------
```

----------------------------------------
- Bitbucket: https://bitbucket.org/lordmauve/pgzero/issue/58

**Comment by lordmauve** [comment]
*Original comment by* **Daniel Pope (Bitbucket: [lordmauve](https://bitbucket.org/lordmauve), GitHub: [lordmauve](https://github.com/lordmauve))**:

----------------------------------------

Thanks for the bug report. It seems likely that your Pygame is not compiled with the same audio codecs as I have. What operating system is this and where did you install Pygame from?

**Comment by lordmauve** [comment]
*Original comment by* **Lumír Balhar (Bitbucket: [frenzymadness](https://bitbucket.org/frenzymadness), GitHub: [frenzymadness](https://github.com/frenzymadness))**:

----------------------------------------

I am building RPM for Fedora so pgzero is built from source code from BitBucket. Should I install some additional package with sound codecs?

**Comment by sellout** [comment]
I am getting this as well (for “WAV audio encoded as Microsoft PCM, 16 bit, stereo, 48000 Hz”). Not running the pgzero tests, but when trying to run escape.py from [Mission Python](https://nostarch.com/missionpython) (there’s a link to the source in the “[Extra Stuff](https://nostarch.com/missionpython#reviews)” section).

I‘m using NixOS, but managing python with venv:

In shell.nix:
``` nix
{pkgs ? import <nixpkgs> {}}:

pkgs.mkShell {
  packages = [pkgs.python3Full];

  LD_LIBRARY_PATH = pkgs.lib.concatStringsSep ":" [
    "${pkgs.glib.out}/lib"
    "${pkgs.libgcc.lib}/lib"
    "${pkgs.libz.out}/lib"
  ];

  shellHook = ''
    python -m venv .venv
    source .venv/bin/activate
    pip install pgzero
  '';
}
```

**Comment by sellout** [comment]
I no longer have this issue. I switched to [a more Nix-heavy approach](https://github.com/sellout/mission-python-nix/blob/main/packages/pgzero.nix) and ditched pip. Works fine now.
