### ISSUE TITLE
Poor error messages when handlers aren't defined to take the correct arguments

### ISSUE THREAD

**Issue by lordmauve** [lordmauve/pgzero#6]
Originally reported by: **Daniel Pope (Bitbucket: [lordmauve](https://bitbucket.org/lordmauve), GitHub: [lordmauve](https://github.com/lordmauve))**

----------------------------------------

While we introspect the handlers at startup time, we do not compare their argument specs to the known argument specs of Pygame's [event objects](https://www.pygame.org/docs/ref/event.html).

If a parameter is mispelled the error will only occur at the moment the event fires, and with an opaque traceback such as:

    Traceback (most recent call last):                                          
      File "/home/mauve/.virtualenvs/pgzero/bin/pgzrun", line 9, in <module>       
        load_entry_point('pgzero==1.0beta1', 'console_scripts', 'pgzrun')()        
      File "/home/mauve/dev/pgzero/pgzero/runner.py", line 36, in main             
        PGZeroGame(mod).run()                                                      
      File "/home/mauve/dev/pgzero/pgzero/game.py", line 167, in run               
        self.dispatch_event(event)                                                 
      File "/home/mauve/dev/pgzero/pgzero/game.py", line 108, in dispatch_event    
        handler(event)                                                             
      File "/home/mauve/dev/pgzero/pgzero/game.py", line 103, in <lambda>          
        return lambda event: handler(**prep_args(event))                           
      File "/home/mauve/dev/pgzero/pgzero/game.py", line 102, in prep_args         
        return {name: get(event) for name, get in param_handlers}                  
      File "/home/mauve/dev/pgzero/pgzero/game.py", line 102, in <dictcomp>        
        return {name: get(event) for name, get in param_handlers}                  
    AttributeError: 'Event' object has no attribute 'buttonz'  

We should fail fast in case of an error like this, with a more helpful error message.

----------------------------------------
- Bitbucket: https://bitbucket.org/lordmauve/pgzero/issue/6

**Comment by lordmauve** [comment]
*Original comment by* **Daniel Pope (Bitbucket: [lordmauve](https://bitbucket.org/lordmauve), GitHub: [lordmauve](https://github.com/lordmauve))**:

----------------------------------------

Resolved with spellchecking as under issue #5, error message will now be

    pgzero.spellcheck.InvalidParameter: on_mouse_down() hook accepts no parameter buttonz; did you mean button?
