### ISSUE TITLE
animate() with bad tween argument raises KeyError with poor message

### ISSUE THREAD

**Issue by lordmauve** [lordmauve/pgzero#95]
The exception raised when a tween does not exist could be better:

```python
>>> animate(alien, 'bounce', angle=180)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mauve/dev/pgzero/pgzero/animation.py", line 216, in animate
    **targets)
  File "/home/mauve/dev/pgzero/pgzero/animation.py", line 154, in __init__
    self.function = TWEEN_FUNCTIONS[tween]
KeyError: 'bounce'
'bounce'
```

**Comment by lordmauve** [comment]
Fixed in #120
